server:
  port: 8503

spring:
  application:
    name: notification-service
  rabbitmq:
    username: furkanguzel
    password: furkanguzel
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
