version: '3.1'

networks:
  furkanguzel:

services:
  # DB and Queue -----------------------
  cassandra:
    image: cassandra
    container_name: fg-cassandra-server
    networks:
      - furkanguzel
    ports:
      - '9042:9042'

  mysql:
    image: mysql
    container_name: fg-mysql-server
    restart: always
    networks:
      - furkanguzel
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3306:3306'

  elasticsearch:
    image: elasticsearch:6.8.5
    container_name: fg-elasticsearch
    networks:
      - furkanguzel
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node

  msrabbitmq:
    image: rabbitmq:3-management
    container_name: fg-msrabbitmq
    networks:
      - furkanguzel
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=furkanguzel
      - RABBITMQ_DEFAULT_PASS=furkanguzel

  # Local Services -----------------------

  fg-account-service:
    image: account-service:10.0.1
    container_name: fg-account-service
    restart: always
    networks:
      - furkanguzel
    environment:
      CONFIG_SERVER_URL: http://fg-config-server:8888
      CASSANDRA_SERVER_HOST: fg-cassandra-server
    ports:
      - '8080:8080'

  fg-ticket-service:
    image: ticket-service:10.0.1
    container_name: fg-ticket-service
    restart: always
    networks:
      - furkanguzel
    environment:
      CONFIG_SERVER_URL: http://fg-config-server:8888
    ports:
      - '8080:8080'

  fg-notification-service:
    image: notification-service:10.0.1
    container_name: fg-notification-service
    restart: always
    networks:
      - furkanguzel
    environment:
      CONFIG_SERVER_URL: http://fg-config-server:8888
    ports:
      - '8080:8080'

  # System Services -----------------------
  fg-config-server:
    image: config-server:10.0.1
    container_name: fg-config-server
    restart: always
    networks:
      - furkanguzel
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      SERVER_PORT: 8888
    ports:
      - '8888:8888'

  fg-eureka-server:
    image: eureka-server:10.0.1
    container_name: fg-eureka-server
    restart: always
    networks:
      - furkanguzel
    environment:
      CONFIG_SERVER_URL: http://fg-config-server:8888
      SERVER_PORT: 8887
    ports:
      - '8887:8887'

  fg-admin-server:
    image: admin-server:10.0.1
    container_name: fg-admin-server
    restart: always
    networks:
      - furkanguzel
    environment:
      EUREKA_SERVICE_URL: http://fg-eureka-server:8888
      SERVER_PORT: 8886
    ports:
      - '8886:8886'

  fg-gateway-server:
    image: gateway-server:10.0.1
    container_name: fg-gateway-server
    restart: always
    networks:
      - furkanguzel
    environment:
      EUREKA_SERVICE_URL: http://fg-eureka-server:8888
      SERVER_PORT: 8885
    ports:
      - '8885:8885'

  fg-hystrix-dashboard:
    image: hystrix-dashboard:10.0.1
    container_name: fg-hystrix-dashboard
    restart: always
    networks:
      - furkanguzel
    environment:
      EUREKA_SERVICE_URL: http://fg-eureka-server:8888
      SERVER_PORT: 8884
    ports:
      - '8884:8884'

  fg-zipkin-server:
    image: zipkin-server:10.0.1
    container_name: fg-zipkin-server
    restart: always
    networks:
      - furkanguzel
    environment:
      EUREKA_SERVICE_URL: http://fg-eureka-server:8888
      SERVER_PORT: 8883
    ports:
      - '8883:8883'